package php

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const iniHeader = `; Generated by Dropserve. Edit PHP settings through Dropserve Settings; this file is regenerated.
display_errors = On
display_startup_errors = On
upload_max_filesize = 64M
post_max_size = 64M
memory_limit = 256M
`

// WriteINI generates Dropserve's development-oriented PHP configuration.
func WriteINI(path, timezone string) error {
	if timezone == "" || strings.EqualFold(timezone, "local") {
		timezone = "UTC"
	}
	content := iniHeader + "date.timezone = \"" + strings.ReplaceAll(timezone, `"`, "") + "\"\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create PHP settings directory: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".php-ini-")
	if err != nil {
		return fmt.Errorf("create PHP settings: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("protect PHP settings: %w", err)
	}
	if _, err := temporary.WriteString(content); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write PHP settings: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("sync PHP settings: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close PHP settings: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("publish PHP settings: %w", err)
	}
	return nil
}
